---
- name: Debian/Ubuntu | Installing repository key
  apt_key: url=http://ossec.alienvault.com/repos/apt/conf/ossec-key.gpg.key

- name: Debian/Ubuntu | Installing repository
  apt_repository: repo="deb http://ossec.alienvault.com/repos/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main" state=present

- name: Debian/Ubuntu | Install ossec-hids
  apt: pkg=ossec-hids
       state=present

- name: Install Debian CIS Root Checks
  get_url:
    url: https://raw.githubusercontent.com/ossec/ossec-hids/master/src/rootcheck/db/cis_debian_linux_rcl.txt
    dest: /var/ossec/etc/shared/cis_rhel6_linux_rcl.txt
    mode: 0660
    owner: root
    group: ossec


- name: Set Distribution CIS filename for Debian/Ubuntu
  set_fact:
    cis_distribution_filename: cis_debian_linux_rcl.txt
  when: ansible_os_family == "Debian"