---
# Tasks specific for RedHat systems

- name: "RedHat | Set some facts"
  set_fact:
    ansible_distribution: CentOS
  when: ansible_distribution == "RedHat"
  tags:
    - always

- name: "RedHat | Install atomicorp repo"
  yum:
    name: "https://www.atomicorp.com/channels/atomic/centos/{{ansible_distribution_major_version}}/x86_64/RPMS/atomic-release-{{ ossec_server_atomic_release }}.el{{ansible_distribution_major_version}}.art.noarch.rpm"
    state: present

- name: "RedHat | Install epel repo"
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present

- name: "RedHat | Install ossec-hids-server"
  yum:
    pkg:
      - ossec-hids
      - ossec-hids-server
    state: present
  tags:
    - init

- block:
    - name: "Set Distribution CIS filename for RHEL5"
      set_fact:
        cis_distribution_filename: cis_rhel5_linux_rcl.txt
      when: ansible_distribution_major_version == "5"

    - name: "Set Distribution CIS filename for RHEL6"
      set_fact:
        cis_distribution_filename: cis_rhel6_linux_rcl.txt
      when: ansible_distribution_major_version == "6"

    - name: "Set Distribution CIS filename for RHEL7"
      set_fact:
        cis_distribution_filename: cis_rhel7_linux_rcl.txt
      when: ansible_distribution_major_version == "7"

    - name: "Set ossec deploy facts for RedHat"
      set_fact:
        ossec_server_config_filename: ossec-server.conf
        ossec_init_name: ossec-hids
        ossec_authd_init_name: ossec-hids-authd
  tags:
    - always
